micronaut:
  application:
    name: pokeapp
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: articunozapdosmoltres
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=pokemons
    username: postgres
    password: mysecretpassword
    driverClassName: org.postgresql.Driver
